### PR TITLE
rewrite

### LINKED ISSUE #13: OwO bot banning the account after not responding to a captcha
This occurs since owo dm's you a captcha and if you dont you will get banned for somtime 
this really decreases the efficiency of the bot and if you left it overnight, owo could ban you perm
Fix: maybe add a system to check if owo dm's you and sleep 
immediately so the bot doesnt ban you

### LINKED ISSUE #16: Verification Information
Cannot recognize the information that prompts for verification

### PR DESCRIPTION
**Pull request by sudo-do**
Script doesnt stop on emergency cases somehow

fixes #16 ,  fixes #13

### CODE REVIEW

**Comment by sudo-do** [comment]
for now i've added a graphical login window,
future update includes:
* command line UI for temux and other things don't have tkinter
* actual UI that shows whats happening

after that I'll add that gems thing for that I need to know every gem's emoji code and it's code
* a json file holds the gems and its data
* a function about the gems

in my opinion, it would be better if I parse all of the messages instead of check last 10 messages every 30 secs. however I'm still thinking on it  to how to do

**Comment by ZeroX1ng** [comment]
image
I hate red line :(

**Comment by sudo-do** [comment]
dude wtf, this is a pr just open a new issue lmao

**Comment by sudo-do** [comment]
noted, thank you for early report 🤠

**Comment by sudo-do** [comment]
fixes #19 
captcha issue
remember me function

**Comment by sudo-do** [comment]
btw just wanted to say im not pushing this pr regularly

**Comment by Ikhari** [comment]
hope u can fix it, because I think the bot is very vulnerable.

**Comment by sudo-do** [comment]
currently working on manage async jobs

**Comment by sudo-do** [comment]
oof

**Comment by sudo-do** [comment]
Fixed #18 
Ongoing tests #13

**Review by legendary0001 — APPROVED** [review]

**Review by ZeroX1ng — APPROVED** [review]

**Comment by ducpro0211kk** [comment]
image
how can I fix it?

**Comment by ducpro0211kk** [comment]
image

**Comment by sudo-do** [comment]
You probably using an old commit

**Comment by ducpro0211kk** [comment]
> You probably using an old commit
I downloaded from here but got error
**https://github.com/sudo-do/discord-selfbot-owo-bot/tree/sudo-do-patch-1**

**Comment by ZeroX1ng** [comment]
image
To be honest, I can't use it either.And when the script starts to run settings, it must manually create the settings.cfg before it can be set up correctly.

**Review by ZeroX1ng — APPROVED** [review]

**Comment by ducpro0211kk** [comment]
is it done?

**Pull request closed without merging**
